// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AuthorComboboxController from "./author_combobox_controller"
application.register("author-combobox", AuthorComboboxController)

import BookChipsController from "./book_chips_controller"
application.register("book-chips", BookChipsController)

import ChatBubbleController from "./chat_bubble_controller"
application.register("chat-bubble", ChatBubbleController)

import CompanyChipsController from "./company_chips_controller"
application.register("company-chips", CompanyChipsController)

import CompanyComboboxController from "./company_combobox_controller"
application.register("company-combobox", CompanyComboboxController)

import ConfirmController from "./confirm_controller"
application.register("confirm", ConfirmController)

import ContactChipsController from "./contact_chips_controller"
application.register("contact-chips", ContactChipsController)

import ContactComboboxController from "./contact_combobox_controller"
application.register("contact-combobox", ContactComboboxController)

import CustomFieldFilterController from "./custom_field_filter_controller"
application.register("custom-field-filter", CustomFieldFilterController)

import CustomFieldFormController from "./custom_field_form_controller"
application.register("custom-field-form", CustomFieldFormController)

import FilmGenreChipsController from "./film_genre_chips_controller"
application.register("film-genre-chips", FilmGenreChipsController)

import FilmLoadBookInfoController from "./film_load_book_info_controller"
application.register("film-load-book-info", FilmLoadBookInfoController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import GlobalSearchController from "./global_search_controller"
application.register("global-search", GlobalSearchController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MarkReadController from "./mark_read_controller"
application.register("mark-read", MarkReadController)

import MessageFormController from "./message_form_controller"
application.register("message-form", MessageFormController)

import MessageListController from "./message_list_controller"
application.register("message-list", MessageListController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)

import ReportSortController from "./report_sort_controller"
application.register("report-sort", ReportSortController)

import RichTextController from "./rich_text_controller"
application.register("rich-text", RichTextController)

import ScrollSaverController from "./scroll_saver_controller"
application.register("scroll-saver", ScrollSaverController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import StaticComboboxController from "./static_combobox_controller"
application.register("static-combobox", StaticComboboxController)

import TabController from "./tab_controller"
application.register("tab", TabController)

import TagSelectController from "./tag_select_controller"
application.register("tag-select", TagSelectController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import ToggleChipsController from "./toggle_chips_controller"
application.register("toggle-chips", ToggleChipsController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
